plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alysson.bcm4375lab'
    compileSdk 35

    defaultConfig {
        applicationId 'com.alysson.marx.v1'
        minSdk 26
        targetSdk 35
        versionCode 11
        versionName '1.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}