plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alysson.bcm4375lab'
    compileSdk 35

    defaultConfig {
        applicationId 'com.alysson.bcm4375lab.remote3'
        minSdk 26
        targetSdk 35
        versionCode 3
        versionName '3.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
