plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alysson.wifispectrum'
    compileSdk 36

    defaultConfig {
        applicationId 'com.alyssonpompeu.wifispectrogrampro'
        minSdk 28
        targetSdk 36
        versionCode 20000
        versionName '2.0.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }

    lint {
        abortOnError true
        checkReleaseBuilds true
    }
}
