pluginManagement {
    repositories {
        google()
        mavenCentral()
        gradlePluginPortal()
    }
}
dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {
        google()
        mavenCentral()
    }
}
rootProject.name = "S21CpuGpuMonitor"
include ':app'
include ':flashlight'
include ':chat'
include ':gpuclock'
include ':hdrboost'
include ':wifiradar'
include ':wifispectrum'
include ':exynostuner'
include ':rx42diag'
include ':rx42dump'
include ':bcm4375lab'
include ':g533probe'
include ':g533rf'
include ':s21lab'
include ':applecontrol'
