package com.alysson.offlineai

import android.content.Context
import com.android.apksig.ApkSigner
import com.android.apksig.ApkVerifier
import kotlinx.coroutines.Dispatchers
import kotlinx.coroutines.withContext
import java.io.File
import java.io.FileOutputStream
import java.security.KeyFactory
import java.security.cert.CertificateFactory
import java.security.cert.X509Certificate
import java.security.spec.PKCS8EncodedKeySpec
import java.util.Locale
import java.util.zip.ZipEntry
import java.util.zip.ZipFile
import java.util.zip.ZipOutputStream

/**
 * Produces concrete artifacts from the compact outputs generated by BuilderStudio.
 * Android artifacts are based on a precompiled, networkless WebView shell and are re-signed
 * locally. Windows artifacts are precompiled Win32 shells whose own executable overlay carries
 * the UI specification. This deliberately avoids a multi-gigabyte compiler toolchain on S21.
 */
class ArtifactBuilder(
    private val context: Context,
    private val packs: PluginPackManager,
) {
    enum class WindowsArch(val fileName: String, val suffix: String) {
        X64("windows/app-shell-x64.exe", "x64"),
        ARM64("windows/app-shell-arm64.exe", "arm64"),
    }

    private val outputDir = File(context.filesDir, "generated-artifacts").apply { mkdirs() }

    suspend fun buildAndroidApk(
        html: String,
        slot: Int,
        suggestedName: String,
        progress: (String) -> Unit,
    ): File = withContext(Dispatchers.IO) {
        require(slot in 1..4) { "Slot Android inválido." }
        val cleanHtml = validateHtml(html)
        val template = requiredPayload("android/slot$slot.apk")
        val keyFile = requiredPayload("signing/builder-key.pk8")
        val certFile = requiredPayload("signing/builder-cert.der")
        val safe = safeName(suggestedName).ifBlank { "app" }
        val unsigned = File(outputDir, "$safe-slot$slot-unsigned.apk")
        val signed = File(outputDir, "$safe-slot$slot.apk")
        unsigned.delete()
        signed.delete()

        progress("Montando APK local…")
        rewriteApk(template, unsigned, cleanHtml)
        progress("Assinando APK local…")
        signApk(unsigned, signed, keyFile, certFile)
        unsigned.delete()

        progress("Verificando assinatura…")
        val result = ApkVerifier.Builder(signed).setMinCheckedPlatformVersion(31).build().verify()
        check(result.isVerified) {
            "O APK foi criado, mas a verificação de assinatura falhou: ${result.errors.joinToString { it.toString() }}"
        }
        signed
    }

    suspend fun buildWindowsExe(
        spec: String,
        arch: WindowsArch,
        suggestedName: String,
        progress: (String) -> Unit,
    ): File = withContext(Dispatchers.IO) {
        val clean = validateWinSpec(spec)
        val shell = requiredPayload(arch.fileName)
        val safe = safeName(suggestedName).ifBlank { "app" }
        val output = File(outputDir, "$safe-${arch.suffix}.exe")
        output.delete()
        progress("Criando executável Windows ${arch.suffix}…")
        shell.inputStream().buffered(1024 * 1024).use { input ->
            FileOutputStream(output).buffered(1024 * 1024).use { out ->
                input.copyTo(out, 1024 * 1024)
                out.write(WINDOWS_MARKER.toByteArray(Charsets.UTF_8))
                out.write(clean.toByteArray(Charsets.UTF_8))
            }
        }
        require(output.length() > shell.length()) { "Falha ao gravar a configuração no executável." }
        output
    }

    suspend fun buildSourceZip(
        generated: String,
        suggestedName: String,
        progress: (String) -> Unit,
    ): File = withContext(Dispatchers.IO) {
        val files = parseSourceFiles(generated)
        require(files.isNotEmpty()) { "Nenhum arquivo de código reconhecido." }
        val safe = safeName(suggestedName).ifBlank { "codigo" }
        val output = File(outputDir, "$safe-fontes.zip")
        output.delete()
        progress("Empacotando código-fonte…")
        ZipOutputStream(output.outputStream().buffered(256 * 1024)).use { zip ->
            files.forEach { (path, body) ->
                zip.putNextEntry(ZipEntry(path))
                zip.write(body.toByteArray(Charsets.UTF_8))
                zip.closeEntry()
            }
            zip.putNextEntry(ZipEntry("README-IA-OFFLINE.txt"))
            zip.write(
                ("Projeto gerado localmente no IA Offline Workspace v3.\n" +
                    "Revise, teste e valide o código antes de uso em produção.\n").toByteArray(Charsets.UTF_8)
            )
            zip.closeEntry()
        }
        output
    }

    private fun requiredPayload(relative: String): File = packs.payloadFile(PluginPackManager.BUILDER_PACK_ID, relative)
        ?: throw IllegalStateException("Instale o pacote Developer Builder Core antes de criar artefatos.")

    private fun rewriteApk(template: File, output: File, html: String) {
        ZipFile(template).use { input ->
            ZipOutputStream(output.outputStream().buffered(1024 * 1024)).use { zip ->
                val entries = input.entries()
                while (entries.hasMoreElements()) {
                    val entry = entries.nextElement()
                    val name = entry.name
                    if (name == "assets/index.html" || name.startsWith("META-INF/")) continue
                    val copy = ZipEntry(name).apply {
                        time = 0L
                        method = ZipEntry.DEFLATED
                    }
                    zip.putNextEntry(copy)
                    if (!entry.isDirectory) input.getInputStream(entry).use { it.copyTo(zip, 256 * 1024) }
                    zip.closeEntry()
                }
                zip.putNextEntry(ZipEntry("assets/index.html").apply { time = 0L })
                zip.write(html.toByteArray(Charsets.UTF_8))
                zip.closeEntry()
            }
        }
    }

    private fun signApk(input: File, output: File, keyFile: File, certFile: File) {
        val privateKey = KeyFactory.getInstance("RSA").generatePrivate(PKCS8EncodedKeySpec(keyFile.readBytes()))
        val certificate = CertificateFactory.getInstance("X.509")
            .generateCertificate(certFile.inputStream()) as X509Certificate
        val signer = ApkSigner.SignerConfig.Builder("IA Offline Local Builder", privateKey, listOf(certificate)).build()
        ApkSigner.Builder(listOf(signer))
            .setInputApk(input)
            .setOutputApk(output)
            .setMinSdkVersion(31)
            .setV1SigningEnabled(true)
            .setV2SigningEnabled(true)
            .setV3SigningEnabled(true)
            .setV4SigningEnabled(false)
            .build()
            .sign()
    }

    private fun validateHtml(raw: String): String {
        var html = raw.trim()
        html = html.removePrefix("```html").removePrefix("```").removeSuffix("```").trim()
        val start = listOf(html.indexOf("<!doctype", ignoreCase = true), html.indexOf("<html", ignoreCase = true))
            .filter { it >= 0 }.minOrNull() ?: -1
        if (start > 0) html = html.substring(start)
        val end = html.lastIndexOf("</html>", ignoreCase = true)
        if (end >= 0) html = html.substring(0, end + 7)
        require(html.contains("<html", ignoreCase = true)) { "A IA não devolveu HTML completo." }
        require(html.toByteArray(Charsets.UTF_8).size <= MAX_HTML_BYTES) { "Interface grande demais para o builder móvel." }
        require(!html.contains("<iframe", ignoreCase = true)) { "iframes não são permitidos no APK offline." }
        require(!REMOTE_RESOURCE.containsMatchIn(html)) { "Recursos remotos não são permitidos no APK offline." }
        return if (html.contains("Content-Security-Policy", ignoreCase = true)) html else injectCsp(html)
    }

    private fun injectCsp(html: String): String {
        val policy = "<meta http-equiv=\"Content-Security-Policy\" content=\"default-src 'self' data: blob:; img-src 'self' data: blob:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'none'; frame-src 'none'\">"
        val head = html.indexOf("<head", ignoreCase = true)
        if (head < 0) return html.replaceFirst(Regex("(?i)<html[^>]*>")) { it.value + "<head>$policy</head>" }
        val close = html.indexOf('>', head)
        return if (close >= 0) html.substring(0, close + 1) + policy + html.substring(close + 1) else html
    }

    private fun validateWinSpec(raw: String): String {
        var spec = raw.trim()
        val begin = spec.indexOf("BEGIN_IASPEC")
        val end = spec.indexOf("END_IASPEC")
        if (begin >= 0 && end > begin) spec = spec.substring(begin + "BEGIN_IASPEC".length, end).trim()
        spec = spec.removePrefix("```").removeSuffix("```").trim()
        val bytes = spec.toByteArray(Charsets.UTF_8)
        require(bytes.size in 8..MAX_WIN_SPEC_BYTES) { "Especificação Windows vazia ou grande demais." }
        val lines = spec.lineSequence().filter { it.isNotBlank() }.toList()
        require(lines.size <= 48) { "A interface Windows excede o limite móvel de componentes." }
        require(lines.any { it.startsWith("APP|") }) { "A especificação Windows precisa começar com APP|Título." }
        val allowed = setOf("APP", "THEME", "TEXT", "INPUT", "RESULT", "CHECK", "BUTTON", "SPACE")
        lines.forEach { line ->
            val kind = line.substringBefore('|').uppercase(Locale.ROOT)
            require(kind in allowed) { "Componente Windows não suportado: $kind" }
        }
        return lines.joinToString("\n")
    }

    private fun parseSourceFiles(raw: String): List<Pair<String, String>> {
        val result = mutableListOf<Pair<String, String>>()
        val lines = raw.lines()
        var path: String? = null
        val body = StringBuilder()
        fun flush() {
            val p = path ?: return
            if (body.isNotBlank()) result += p to body.toString().trimEnd() + "\n"
            path = null
            body.clear()
        }
        for (line in lines) {
            if (line.startsWith("BEGIN_FILE ")) {
                flush()
                val candidate = line.removePrefix("BEGIN_FILE ").trim().trim('"', '\'', '`')
                require(isSafeSourcePath(candidate)) { "Caminho de fonte inválido: $candidate" }
                path = candidate
            } else if (line.trim() == "END_FILE") {
                flush()
            } else if (path != null) {
                body.appendLine(line)
                require(body.length <= MAX_SOURCE_FILE_CHARS) { "Arquivo de fonte grande demais." }
            }
        }
        flush()
        require(result.size <= 12) { "Muitos arquivos para um único ciclo móvel." }
        return result
    }

    private fun isSafeSourcePath(path: String): Boolean = path.isNotBlank() && path.length <= 120 &&
        !path.startsWith('/') && !path.contains("\\") && !path.split('/').any { it == ".." || it.isBlank() }

    private fun safeName(value: String): String = value.lowercase(Locale.ROOT)
        .replace(Regex("[^a-z0-9._-]+"), "-")
        .trim('-')
        .take(48)

    companion object {
        private const val MAX_HTML_BYTES = 384 * 1024
        private const val MAX_WIN_SPEC_BYTES = 256 * 1024
        private const val MAX_SOURCE_FILE_CHARS = 180_000
        private const val WINDOWS_MARKER = "\nIAPAYLOAD1\n"
        private val REMOTE_RESOURCE = Regex("(?i)(src|href)\\s*=\\s*[\"']\\s*(https?:)?//")
    }
}
