plugins {
    id 'com.android.application'
}

android {
    namespace 'com.alysson.hdrboost'
    compileSdk 35

    defaultConfig {
        applicationId 'com.alysson.hdrboost'
        minSdk 24
        targetSdk 35
        versionCode 3
        versionName '1.1.0-root'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
